
name: Authenticate to Google Cloud

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: "google-github-actions/auth@v2.1.3"
        with:
          credentials_json: "${{ secrets.OTTO }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"

      - name: "Set region for Cloud Run"
        run: "gcloud config set run/region europe-north1"

      - name: "Deploy to Cloud Run"
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DATABASE: ${{ secrets.POSTGRES_DATABASE }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
        run: |
          gcloud run deploy slowchat \
            --source . \
            --allow-unauthenticated \
            --update-env-vars POSTGRES_URL=${{ secrets.POSTGRES_URL }},POSTGRES_USER=${{ secrets.POSTGRES_USER }},POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }},POSTGRES_DATABASE=${{ secrets.POSTGRES_DATABASE }},POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} \
            --platform managed

